# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f090c91b6175208bc399fac6b9d1103b84a6abdd2cf6ebf92a10eba6cacce4c1ab0ad9a82a8d385f2720911bee86c04b24f07ec42d8b0c8f25b141acaf3249

test:
  secret_key_base: 41dff9b695aa3494dc63da0219d73368f722e043d2c83937cd507940610a28ddd57e0a5ab83c93bfd8e890c11df2250c785b1c32956b014e8e4dc812dcc2cf15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
